# Generated by Django 5.0.6 on 2024-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainstation',
            name='station',
        ),
        migrations.AddField(
            model_name='trainstation',
            name='station_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
