# Generated by Django 5.0.6 on 2024-08-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0003_alter_station_options_remove_station_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Train.station', unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Train.trainmodel')),
            ],
        ),
    ]
