# Generated by Django 5.0.6 on 2024-09-27 00:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0004_alter_coachclass_coach_name_alter_runson_day_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coachclass',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('coach_name'), name='unique_lower_coach_name'),
        ),
        migrations.AddConstraint(
            model_name='runson',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('day_name'), name='unique_lower_day_name'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_station_name'),
        ),
    ]
